require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"css",
		"dockerfile",
		"elm",
		"fish",
		"gitcommit",
		"go",
		"gomod",
		"graphql",
		"html",
		"http",
		"javascript",
		"json",
		"lua",
		"python",
		"rust",
		"toml",
		"yaml",
	},
	highlight = { enable = true, disable = {} },
	indent = { enable = true },
	endwise = { enable = true },
})
