vim.g.mapleader = " "
vim.opt.clipboard = "unnamed,unnamedplus"
vim.opt.colorcolumn = "80"
vim.opt.completeopt = "menu,menuone,preview,noselect"
vim.opt.cursorline = true
vim.opt.expandtab = true
vim.opt.foldenable = false
vim.opt.ignorecase = true
vim.opt.laststatus = 3
vim.opt.mouse = "a"
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.scrolloff = 5
vim.opt.shell = "/bin/zsh"
vim.opt.shiftwidth = 4
vim.opt.shortmess = vim.opt.shortmess + "c"
vim.opt.smartcase = true
vim.opt.softtabstop = 4
vim.opt.swapfile = false
vim.opt.tabstop = 4
vim.opt.termguicolors = true
vim.opt.winborder = "bold"
